10 REM TEST 36 - WHILE WITH STRING SENTINEL IN DATA
20 PRINT "=== TEST 36: WHILE STRING SENTINEL ==="
30 DATA "APPLE", "BANANA", "CHERRY", "DONE", "EXTRA"
40 READ W$
50 WHILE W$ <> "DONE"
60 PRINT W$
70 READ W$
80 WEND
90 PRINT "DONE MARKER HIT"
100 PRINT "EXPECTED: APPLE  BANANA  CHERRY  DONE MARKER HIT"
110 END
