10 REM TEST42 - MULTI STATEMENT CONDITIONAL
20 PRINT "=== TEST 42: MULTI STATEMENT CONDITIONAL ==="
30 LET A = 1
35 PRINT "A = 1"
40 IF A = 1 THEN PRINT "A" : PRINT "B" ELSE PRINT "C" : PRINT "D"
50 LET A = 2
60 PRINT "A = 2"
70 IF A = 1 THEN PRINT "A" : PRINT "B" ELSE PRINT "C" : PRINT "D"
80 PRINT "EXPECTED: A=1 A B A=2 C D"