10 REM TEST 46 - AUTO DIM ERROR CASES (EXPECT RUNTIME ERROR)
20 PRINT "=== TEST 46: AUTO DIM SUBSCRIPT OUT OF RANGE ==="
30 REM A IS AUTO DIM'D TO (0 TO 10) BY THE FIRST LINE.
40 LET A(5) = 1
50 PRINT "A(5) SET OK"
60 REM AUTO DIM DOES NOT GROW - INDEX 11 IS OUT OF RANGE AND MUST ERROR.
70 PRINT "ABOUT TO USE A(11) - THIS SHOULD PRODUCE A RUNTIME ERROR"
80 LET A(11) = 1
90 PRINT "SHOULD NOT REACH HERE"
