10 REM TEST 47 - RE-DIM WITHOUT CLEAR IS A RUNTIME ERROR
20 PRINT "=== TEST 47: DIM AFTER USE / RE-DIM ==="
30 LET A(5) = 42
40 PRINT "A AUTO DIMENSIONED BY USE, A(5) = "; A(5)
50 PRINT "ABOUT TO RE-DIM A - THIS SHOULD PRODUCE A RUNTIME ERROR"
60 DIM A(20)
70 PRINT "SHOULD NOT REACH HERE"
